import type {Metadata} from "next";
import {Inter} from "next/font/google";

import "./globals.css";

import Navbar from "@/components/navbar";

import {ThemeProvider, UnitProvider} from "./providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en" suppressHydrationWarning>
    <body className={`${inter.className} root-body`}>
      <ThemeProvider>
        <UnitProvider>
          <Navbar />
          {children}
        </UnitProvider>
      </ThemeProvider>
    </body>
  </html>
);

export default RootLayout;
